version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  mangalibrary:
    container_name: mangalibrary
    build: .
    env_file: .env
    ports:
      - 5000:5000
    command: bash -c "python3 db_create.py && flask run --host 0.0.0.0"
    restart: always

  celery:
    container_name: celery
    env_file: .env
    build: .
    command: celery -A worker.celery worker --loglevel=INFO -Q email
    restart: always

  postgres:
    container_name: postgres
    image: postgres:10
    env_file: .env
    ports:
      - 5432:5432
    restart: always